version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo yarn add global npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-packages
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn test
      - run:
          name: build-project
          command: yarn generate:gh-pages
      - run:
          name: Install and configure dependencies
          command: |
            yarn add gh-pages -D
            git config user.email "ts.roberto@gmail.com"
            git config user.name "maninkari"
      - add_ssh_keys:
          fingerprints:
            - '81:76:60:4b:71:f6:79:36:1c:f2:1e:3b:1e:f5:09:38'
      - run:
          name: Deploy docs to gh-pages branch
          command: './node_modules/.bin/gh-pages --dotfiles --message "[skip ci] Updates" -d dist'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml
